# Generated by Django 2.0.7 on 2018-12-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('roll', models.CharField(choices=[('pr', 'Professor'), ('mr', 'Mester'), ('ms', 'miss')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ee', 'Electrical Engineering'), ('ce', 'Computer Engineering'), ('me', 'Mechanical Engineering'), ('ie', 'Industrial Engineering'), ('ma', 'Mathematiues'), ('ph', 'Physics')], max_length=2)),
                ('dept_admin', models.CharField(max_length=300)),
                ('phonenum', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='dorms',
            fields=[
                ('dorm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dorm_name', models.CharField(max_length=300)),
                ('num_rooms', models.IntegerField()),
                ('num_facil', models.IntegerField()),
                ('phonenum', models.CharField(max_length=11)),
                ('dorm_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.admins')),
            ],
        ),
        migrations.CreateModel(
            name='majors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.CharField(choices=[('ee', 'Electrical Engineering'), ('ce', 'Computer Engineering'), ('me', 'Mechanical Engineering'), ('ie', 'Industrial Engineering'), ('ma', 'Mathematiues'), ('ph', 'Physics')], max_length=2)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dept')),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_statue', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('type_degree', models.CharField(choices=[('bs', 'bacholers'), ('ms', 'masters'), ('dr', 'phd')], max_length=300)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.majors')),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('worker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=300)),
                ('worker_duty', models.CharField(max_length=300)),
                ('worker_age', models.IntegerField()),
                ('worker_sex', models.CharField(choices=[('fe', 'female'), ('ma', 'male')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.students'),
        ),
        migrations.AddField(
            model_name='admins',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dept'),
        ),
        migrations.AddField(
            model_name='admins',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.majors'),
        ),
    ]
