# Generated by Django 2.0.7 on 2018-12-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='dept_admin',
        ),
    ]
