# Generated by Django 2.0.7 on 2019-01-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190101_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.students'),
        ),
    ]
