# Generated by Django 2.0.7 on 2019-01-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190101_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.students'),
        ),
    ]
